### ISSUE TITLE
Q&A channel for longer discussions

### ISSUE THREAD

**Issue by behoppe** [OpenCilk/www.opencilk.org#11]
We plan for a suite of Q&A channels, including StackOverflow for typical how-to problems and GitHub Issues for bugs and most feature requests. In addition to those, we want a channel for longer discussions (e.g. more complicated feature requests) and announcements.

A mailing list would be a good choice for this channel, but there are tradeoffs to balance.

- We have mailing lists now, and we could configure a similar Mailman list as we desire, right beside them, but that list would have an mit.edu domain, which might unnecessarily tie our brand to MIT.
- We could deploy our own instance of Mailman. This was the proposed plan, but we see that installing and running Mailman is a very heavy lift, suited only for experienced Linux sysadmins.

So we need to figure out where our long-form discussion channel will reside. One of those options above? Or another option not yet listed.

**Comment by neboat** [comment]
We could consider GitHub Discussions.  I've seen some projects use GitHub Discussions, and it seemed like they work well.  But I don't have a ton of experience with them.

GitHub Discussions is currently enabled on our repositories, if you want to take a look.

**Comment by behoppe** [comment]
Thanks, TB. Great idea. I will take a look.

**Comment by behoppe** [comment]
I am thinking about piloting GitHub Discussions, by starting one (or a few) threads where it could be great to hear from the team. Possible topics are
- What are some good blog ideas? (I have a starting list from Charles)
- What kinds of application, tool, and benchmark integrations would be good to promote?
- More about our (community) resource list?
- Other?

What do you think? Then, when/if I start Discussions, which repository should I use? Maybe opencilk-project? I created a separate Issue-tracker for the website (which I'm happy to revisit if we want) but it seems like we really want a single place for OpenCilk community discussion and announcements. Right?

**Comment by neboat** [comment]
Yes, GitHub provides facilities for moderating discussions: https://docs.github.com/en/site-policy/github-terms/github-community-guidelines#what-if-something-or-someone-offends-you.

**Comment by behoppe** [comment]
Thanks @dcurtisatmit and @neboat. I will pilot GitHub Discussions for us. 

Are you OK with using opencilk-project as the host repository for our discussions?

**Comment by neboat** [comment]
That's fine with me.
