### ISSUE TITLE
Image display and organization

### ISSUE THREAD

**Issue by behoppe** [OpenCilk/www.opencilk.org#13]
We want articles, especially blog posts, to feature inline images. Markdown offers very basic support for this. Would be nice to have something that can resize and float images, without requiring the author to code that directly with HTML/CSS.

Also, we may soon want to offer more than one "img" folder.

**Comment by ailiop** [comment]
> We want articles, especially blog posts, to feature inline images. Markdown offers very basic support for this. Would be nice to have something that can resize and float images, without requiring the author to code that directly with HTML/CSS.

One solution to this might be to make [shortcode](https://www.11ty.dev/docs/shortcodes/) macros that expand to appropriate HTML/CSS code.

**Comment by ailiop** [comment]
It would also be nice to support vector-graphics images (in .svg, .xml, or .pdf format) to avoid resolution loss, if possible.

**Comment by behoppe** [comment]
Thanks, @ailiop, 2a2d08d1e6f3d922e68673150d85bf4e0fb02335 implements `img` as a shortcode, along with `imgRight` and `imgLeft`. I am not 100% sure that shortcodes are better than using HTML/CSS, but here's what I came up with. What do you think?

`{% img "/img/filename.ext", "size" %}`
Displays centered image (as a CSS block), sized so that neither its width nor height exceed optional "size", which defaults to 400px.

`{% imgRight "/img/filename.ext", "size" %}`
`{% imgLeft "/img/filename.ext", "size" %}`

Displays image floated to right or left, sized so that neither its width nor height exceed optional "size", which defaults to 400px.

See [What the $#@! is parallelism](https://www.opencilk.org/posts/2022-05-20-what-the-is-parallelism-anyhow/) for an example.

**Comment by ailiop** [comment]
I think that works pretty well.

Looking at what the `img` shortcode expands to in 2a2d08d1e6f3d922e68673150d85bf4e0fb02335, I think the shortcode is much simpler than writing that as HTML.  I suppose a combination of HTML classes and corresponding CSS styles might accomplish pretty much the same thing — but if we are to use shortcodes for other non-plain-Markdown effects that maybe aren't that simple (e.g., alert/note boxes), then I think it's better to use shortcodes for all of them.

Regarding wrapped images: I wonder to what extent we can (or want to) control what text gets wrapped around the image and what happens where there is very little or too much space for text next to, say, an `imgRight` image.  For example:

- On my desktop monitor, if I zoom out enough, the height of the DAG image becomes greater than the height of the text for the "A model for multithreaded execution" section.  Hence, the next section body also gets wrapped around the DAG image.  This is not really an issue in this case, but it is conceivable that this behavior might be undesirable.  Imagine, for instance, a post where two consecutive sections or paragraphs respectively refer to a "before" and "after" image.
- On my phone (in portrait mode),  the DAG image gets displayed before the paragraph that refers to it.  This makes the accompanying text ("the figure [on the] right illustrates a multithreaded dag...") awkward and potentially confusing.

I am not sure what is the right way to deal with such issues while still using inline images.  One (possibly bad) approach might be to somehow use paired shortcodes as a way to indicate the content that may be wrapped around an inline image..?

**Comment by behoppe** [comment]
The urgent part of this issue seem done IMO, and I am leaving it open because there are still longer-term questions in the comments.

**Comment by behoppe** [comment]
Another possibility for images: As mentioned in #140, if you pre-size an image file, then you can set the optional width argument of the `img` shortcode to `100%` and thereby limit the growth of the image (while still allowing it to shrink).

We may revisit this if/when we desire sophisticated control of wrapping, but I am closing this issue for now.
