### ISSUE TITLE
Inline code gets linewrapped

### ISSUE THREAD

**Issue by VoxSciurorum** [OpenCilk/www.opencilk.org#143]
Text in markdown backticks, rendered in code style, can be split across lines at places where ordinary text would not be split.
<img width="1059" alt="Screen Shot 2022-08-17 at 11 59 51 AM" src="https://user-images.githubusercontent.com/60116679/185187630-403175ab-bad0-4829-9e1c-6b3ad50aad75.png">

**Comment by VoxSciurorum** [comment]
Safari 15.6 on macOS 12.5.  Also seen before upgrading to the latest OS.

**Comment by behoppe** [comment]
Thanks @VoxSciurorum I have tested a fix with https://github.com/behoppe/www.opencilk.org/pull/6 and expect to merge that into the main branch here in a few days.
