### ISSUE TITLE
Minor issues with /doc/users-guide/getting-started/

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/www.opencilk.org#172]
**Issues**

1.  In section **Running the program on multiple cores** The version of the fib code you ran for the example is different than the example linked in the tutorial section https://github.com/OpenCilk/tutorial/blob/main/fib.c.  Specifically the version you ran also printed the time, and the version in the repo does not.
2. In section **Using Cilkscale** you mention tutorial program qsort_wsp.c, which I was unable to find.  I would expect to find it in the same tutorial repo linked at the top of the page 

**Improvements**
The tutorial repo can be updated with the missing and correct version of the programs.

**Comment by behoppe** [comment]
Thanks @wheatman for the report.

@ailiop, thanks for addressing this with your update to the tutorial repo. Is there anything else we need to do?

**Comment by ailiop** [comment]
Thank you @wheatman!

@behoppe Probably not: once the tutorial repo PR is merged, the information in the Getting Started page would be correct.  I would just like to see if @neboat has a different opinion on what the tutorial repo should be like.
