### ISSUE TITLE
tags being cut off on https://www.opencilk.org/tags/

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/www.opencilk.org#220]
**Issues**
The tags are being cut off visually on https://www.opencilk.org/tags/

They seem to do so on many different screen sizes and unless I make the screen small enough that it switches from 2 columns down to 21, they are always cut off.

**System information**
I am using chrome on windows 

see the far left of 

![image](https://github.com/OpenCilk/www.opencilk.org/assets/6783551/3ea2a50d-cf4f-4afe-b5af-57cb62cd72c4)

**Comment by behoppe** [comment]
Thanks @wheatman for the report. The tags page is quite rough, I have to say, so I'm trying to understand the specific problem that you are flagging. Is it the left sidebar, where the screenshot indicates tags ending abruptly at "mutex"? On my machine, that sidebar has vertical scrolling, which becomes visible when you mouse-over, and so there is not, in fact, anything being cut off.

Now might be a good time to consider briefly what we want in a tags page. The features I would most want start with some evident order of the tags (e.g. alphabetical), and maybe also include a summary of pages that use each tag (e.g. as seen in https://www.opencilk.org/tags/work/). I'm curious what you think?

**Comment by wheatman** [comment]
If you look at the far left of the image the words are all cut off.
For example
Release has no R
Tools has no T
Glossary has no G and so on

**Comment by behoppe** [comment]
Thanks @wheatman. It should be fixed now in PR #221. Could you please confirm?

**Comment by wheatman** [comment]
yes, it looks fixed in the deploy preview (https://deploy-preview-221--sage-licorice-6da44d.netlify.app/tags/)
