### ISSUE TITLE
Sidebar organization/aesthetics 

### ISSUE THREAD

**Issue by timkaler** [OpenCilk/www.opencilk.org#25]
I have a few comments on the side bar.

1) The buttons with colored backgrounds (e.g. "User's Guide" when on the getting started page) will probably look better if they fill the entire sidebar. The sidebar has fixed width, so there shouldn't be any issues. If there are multiple such buttons then having them fill the sidebar will make their left and right borders align which looks cleaner.

2) Why is the "On this page" menu separate from the primary sidebar menu? If I am on the "Getting started" page, it seems like the contents of "On this page" should appear right under the "Getting started" entry in the sidebar --- i.e. the sidebar menu should allow nesting.

3) I don't see why the sidebar needs to have collapsable menus --- is there a good justification for this?

**Comment by behoppe** [comment]
Hi, Tim, and thanks for these good comments. The short answer to all of your comments is that the current sidebar design represents a compromise between (1) my current knowledge of CSS, Javascript, etc., and (2) design policies built into Bootstrap 5 that strongly discourage nested drop-down menus.

My ideal vision for the left sidebar would be nested and expanding/collapsing dynamically section by section, based on user selections. And I'd love for it to minimize or somehow go away when the screen is very small or the menu is not desired.

The two separate menus, each independently collapsible, are intended to provide (1) context that is more specific than the breadcrumb, and (2) shortcuts to navigate a long page. The collapsing is there for the event that the top menu is long, and then simply for consistency's sake with the bottom one.

It is not an ideal set-up by any means, and I think what you're asking for is probably very similar to what I am also hoping to achieve. I have no shortage of Google search results on how to do this stuff, but so far I have not had success implementing any of them. I would welcome assistance, if you are interested.

**Comment by behoppe** [comment]
Today I made the headers full-width and removed the button & collapsing functionality.

**Comment by behoppe** [comment]
IMO the biggest shortcoming of the left sidebar (among many) is that the table of contents scrolls away when it's large and you use it. For example, clicking on a glossary entry will typically take the TOC off the screen.

I see that the sidebar scrolls when I use
```<div id="sidebar" class="collapse show px-3 pt-0 vh-100 overflow-scroll" ...
```
(I had not used `vh-100` before, which is necessary for the `overflow-scroll` to work.)

And so what remains is to fix the sidebar so that the "main body" and the sidebar scroll independently of each other.

**Comment by behoppe** [comment]
I implemented independent scrolling for sidebar and main body with #135, which I have linked to this issue. I'll wait and see if others (like Tim, @dcurtisatmit, @neboat) agree that it's an improvement.

**Comment by behoppe** [comment]
the scrolling somehow got reverted and I put it into #152, so this issue will close with that PR.
