### ISSUE TITLE
Ubuntu 20.04 stdio.h not found

### ISSUE THREAD

**Issue by dcurtisatmit** [OpenCilk/www.opencilk.org#38]
OpenCilk compiling on Ubuntu 20.04 has an issue:
../bin/clang -fopencilk -O3 fib.c -o fib
fib.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
I assume some other generic C packages need to be installed?

apt-get install libc6-dev

**Comment by behoppe** [comment]
Closing this issue, as it is subsumed by #39.
