### ISSUE TITLE
Netlify CMS fails to connect with Git gateway

### ISSUE THREAD

**Issue by behoppe** [OpenCilk/www.opencilk.org#61]
**Describe the website error**
@cleiserson cannot log in to the admin panel. Git gateway error: [object Object].

**Which page of the site**
https://www.opencilk.org/admin

**Expected behavior**
I am able to log in by using "Continue with GitHub." 

**System information**
Charles was using his Mac with Firefox.

**Additional context**
We tried clearing browser history. This did cause the browser to try again and make a fresh connection, but the same error would happen anyway. Git gateway error: [object Object]. We looked [here](https://answers.netlify.com/t/git-gateway-error/12220/4) and I added a `repo` field to the `admin/config.yml` but that did not help.

**Comment by beh333** [comment]
I disabled git-gateway from Netlify and then re-connected, and now it works again.
