### ISSUE TITLE
https://sage-licorice-6da44d.netlify.app/doc/users-guide/getting-started/

### ISSUE THREAD

**Issue by dcurtisatmit** [OpenCilk/www.opencilk.org#64]
Apologies for not putting this issue in the right place.

There is an issue in the section within the getting started page on using cilkscale

python3 /opt/opencilk/share/Cilkscale_vis/cilkscale.py \
    -c qsort -b qsort-bench --args 10000000

This command should be

python3 /opt/opencilk/share/Cilkscale_vis/cilkscale.py \
    -c ./qsort -b ./qsort-bench --args 10000000

or else you get an error
    /bin/sh: 1: qsort: not found

(An alternate fix is to have "." in your path, but this is deprecated due to security issues.)

**Comment by behoppe** [comment]
Thank you @dcurtisatmit. I will merge this with #59, which is about "Getting started."
