### ISSUE TITLE
/doc/users-guide/build-opencilk-from-source/

### ISSUE THREAD

**Issue by dcurtisatmit** [OpenCilk/www.opencilk.org#71]
** Assignee Roles**
- Owner: @neboat: Owner
- Reviewer: @VoxSciurorum
- Tester: @dcurtisatmit

**Issues**
Confirm that opencilk builds from source on Ubuntu 18.04

**Comment by DorothyCurtis** [comment]
V2RC2 builds ok on Ubuntu 18.04

**Comment by behoppe** [comment]
We published pr #99 today.
