### ISSUE TITLE
Dummy issue to check ping notifications

### ISSUE THREAD

**Issue by ailiop** [OpenCilk/www.opencilk.org#75]
This is a comment without pings.

**Comment by ailiop** [comment]
And one that pings @ailiop

**Comment by ailiop** [comment]
Try again @ailiop

**Comment by ailiop** [comment]
Leaving this issue open for now, since neither @dcurtisatmit nor @ailiop actually received notifications within 5'.

To be revisited.

**Comment by behoppe** [comment]
@dcurtisatmit and @ailiop -- you did not receive notifications within 5 minutes? I wonder what's up.

**Comment by behoppe** [comment]
I have just created an issue that reports this problem. Then I remembered we have this issue that demonstrates the very problem I was reporting. I will close this issue and we can refer to #115 for problems with notifications. I hope we fix this somehow.
